# Generated by Django 4.0.1 on 2022-01-30 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='client',
            field=models.FileField(default='client1', max_length=50, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 2, 31, 22, 556398, tzinfo=utc)),
        ),
    ]
