# Generated by Django 4.0.1 on 2022-01-30 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_cashrecord_client_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 2, 37, 43, 28287, tzinfo=utc)),
        ),
    ]
