# Generated by Django 4.0.1 on 2022-01-30 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_alter_cashrecord_date_alter_cashrecord_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 13, 46, 22, 518537, tzinfo=utc)),
        ),
    ]
