# Generated by Django 4.0.1 on 2022-02-02 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 3, 46, 12, 750460, tzinfo=utc)),
        ),
    ]
