# Generated by Django 4.0.1 on 2022-02-07 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 11, 46, 38, 122706, tzinfo=utc)),
        ),
    ]
