# Generated by Django 4.0.1 on 2022-02-07 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 12, 44, 33, 583423, tzinfo=utc)),
        ),
    ]
