# Generated by Django 4.0.1 on 2022-03-03 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_alter_cashrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 14, 44, 46, 268940, tzinfo=utc)),
        ),
    ]
