# Generated by Django 4.0.1 on 2022-02-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingRecord',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('budget', models.FloatField()),
                ('projectname', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_market_record',
            },
        ),
    ]
