# Generated by Django 4.0.1 on 2022-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingrecord_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingrecord',
            name='remark',
            field=models.CharField(max_length=2000),
        ),
    ]
