# Generated by Django 4.0.1 on 2022-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_marketingrecord_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingrecord',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingrecord',
            name='remark',
            field=models.TextField(),
        ),
    ]
